# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.CharField(max_length=70, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
    ]
