# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 20:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191021_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
